### ISSUE TITLE
azure function context.done

### ISSUE THREAD

**Issue by dafian** [vjrantal/bot-sample#3]
Hi,
thanks for those example, are pretty clear.
But while I was really testing the Azure Function I remembered about the context object and its "done" function that should be called as soon as the computation is ended. Is there any clear way on how and when it should be invoked?

Thank you again.

**Comment by vjrantal** [comment]
@dafian The logic that tells the Functions runtime that the computation is ended is included in the Microsoft Bot Framework SDK code so you are not responsible for calling a done function. If you see some unexpected behavior when you try the code in this repository, please open an issue with the error message and reproduce steps. Thanks for your comment!
