### ISSUE TITLE
Restify and AWS lambda

### ISSUE THREAD

**Issue by sharmmoh1983** [vjrantal/bot-sample#4]
How api/messages are getting triggered in lambda serverless

**Comment by vjrantal** [comment]
@sharmmoh1983 The AWS Lambda deployment was done via the Serverless framework. You can see the configuration at https://github.com/vjrantal/bot-sample/blob/master/serverless.yml which defines the HTTP event and to which handler that event is routed to.

If possible, please try the deployment to AWS via the Serverless framework and if that doesn't work, please write here the error message you are getting.

**Comment by sharmmoh1983** [comment]
I want to add host some rest apis also with the bot functionality but your serverless solution will just expose one event. I have  exposed express sever also using bot functionality but everytime only api/messages gets invoked and not Universal Bot connector method . I know it is to do with connector.listen() method.

**Comment by sharmmoh1983** [comment]
I am using claudia js framework( same as serverless) to use bot framework. But it seems not work.

Can you help me in tweaking connector.listen( for claudiajs 
https://claudiajs.com/

**Comment by vjrantal** [comment]
@sharmmoh1983 Since this is not really an issue of the code in this repository, I will close it.

However, if you have your project somewhere in GitHub, you can send the pointer as a comment and someone might be able to have a look.
